insert into entreprise(id, nom, siret, heure_ouverture, heure_fermeture, search_distance, search_days, temps_rdv, jours_ouverture, time_step) values (1, 'Samson Multi Services', '54205118000066', '08:00:00', '19:00:00', 20, 45, 90, 124, 30);

insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1000, '1', 'Rue du Général Sarrail', '33400', 'Talence', 'ChIJQ9EmEm8nVQ0Reo9XUdeNnQ4', '44.7992055', '-0.590534') ;
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1001, '58', 'route de Bordeaux', '33220', 'PORT DE SAINTE FOY', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1002, '35', 'lotissement Saussus', '33250', 'PAUILLAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1003, '6', 'Rue de Lyon', '33700', 'Mérignac', 'ChIJdRkenWnYVA0RCYx1uCNS_dE', '44.8248137', '-0.6181942');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1004, '4', 'Rue de Belfort', '33600', 'Pessac', 'ChIJ4XW64t3bVA0Ro20Wjkc9ePI', '44.7929726', '-0.6820988');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1005, '15', 'Avenue Aristide Briand', '33600', 'Pessac', 'ChIJo2vYau_YVA0RjFRo7bP79AM', '44.7986522', '-0.628749999999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1006, '6', 'avenue la grande haie', '33540', 'SAUVETEERE DE GUYENNE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1007, null, 'avenue Aristide Briand', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1008, '7', 'Rue Hector Berlioz', '33400', 'Talence', 'ChIJ4WCPeGknVQ0R6x-wfoznuEE', '44.7952526', '-0.5876891');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1009, '6', 'cité de chante oiseau', '33920', 'SAINT CHRISTOLY DE BLAYE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1010, '33', 'Rue Maréchal Gallieni', '33200', 'Bordeaux', 'ChIJJ8guHSPYVA0RrnP7PQn08Y0', '44.8411123', '-0.622992699999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1011, '10', 'rue du merle', '33700', 'MERIGNAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1013, '24', 'Rue Jacques Cartier', '33600', 'Pessac', 'ChIJDY4JmILZVA0RhI3XdyHleE4', '44.8116905', '-0.669009299999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1014, '3', 'chemin du champ d''Auron', '33133', 'GALGON', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1015, '29', 'route de l''estuaire', '33710', 'COMPS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1016, '4', 'Allée Laennec', '33600', 'Pessac', 'ChIJs7OcTxDZVA0RkoO3lFk3lpg', '44.8003611', '-0.6506592');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1017, '34 bis', 'La Croix', '33710', 'BOURG', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1018, null, null, '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1019, '14', 'caussette', '33350', 'SAINT PEY DE CASTETS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1020, null, 'Lieu-dit La Pillaudiere', '79200', 'LA CHAPELLE BERTRAND', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1021, '12', 'Allée Jean Giraudoux', '33600', 'Pessac', 'ChIJS8cvgJ3ZVA0RHaKvON3X12w', '44.8112945', '-0.6654136');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1022, '7', 'chemin aouguitche', '33610', 'CESTAS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1024, '9', 'rue Armand Roux', '33180', 'VERTHEUIL', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1025, '5', 'route des cotes de bourg', '33710', 'BAYON SUR GIRONDE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1026, '36', 'allée des bruyeres', '33127', 'ST JEAN D''ILLAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1027, '11', 'Allée des Cosmos', '33170', 'Gradignan', 'ChIJuZXZ-7DYVA0RTcialMoZExg', '44.7814242', '-0.6136214');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1028, null, 'chemin de la gaillarde', '33710', 'TEUILLAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1029, '1', 'rue du 19 mars', '33340', 'BLAIGNAN', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1030, '9', 'le Moulin', '33210', 'LEOGEATS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1031, '360', 'Avenue de Guyenne', '40600', 'Biscarrosse', 'ChIJJ-qrV5aAVA0RpwI2pyCtHzY', '44.4062528', '-1.1565931');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1032, '250', 'Allée de Piroulet', '40600', 'Biscarrosse', 'ChIJ8bNjMIyAVA0R2bTDndPIQqE', '44.4082426', '-1.1670471');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1033, '155', 'Rue Fernand Audeguil', '33000', 'Bordeaux', 'ChIJoXZZhZQnVQ0R7FZF-NhKGII', '44.8286329', '-0.586435199999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1034, '39', 'Rue Félix Faure', '33600', 'Pessac', 'ChIJESqJTGTZVA0RR1Gj25dO7T8', '44.7986126', '-0.670319899999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1035, '3', 'rue du bac', '33230', 'SABLONS LES PEINTURES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1036, null, 'Avenue Aristide Briand', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1037, '19', 'Avenue Aristide Briand', '33600', 'Pessac', 'ChIJXaF0F-_YVA0RsWg0dKs11qU', '44.7985347', '-0.6280646');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1038, null, 'rue de la princesse', '33700', 'MERIGNAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1039, '19', 'Rue Saint-Jacques', '33600', 'Pessac', 'ChIJMV88gPvYVA0R6yPmuAxLW14', '44.8043772', '-0.6345441');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1040, '40', 'Avenue de l''Océan', '40550', 'Léon', 'Eio0MCBBdmVudWUgZGUgbCdPY8OpYW4sIDQwNTUwIEzDqW9uLCBGcmFuY2U', '43.8747919', '-1.3038105');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1041, null, null, '33', 'CESTAS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1042, '20', 'rue des villas', '33200', 'BORDEAUX', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1043, '41', 'rue val de bellassise', '33560', 'SAINT EULALIE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1044, null, null, '40600', 'BISCAROSSE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1045, '7', 'Allée de la Cantine', '33830', 'Belin-Béliet', 'ChIJ3zaQ697wVA0RfLLAi6zQu2k', '44.4876709', '-0.7879482');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1046, '40', 'Avenue de l''Océan', '40550', 'Léon', 'Eio0MCBBdmVudWUgZGUgbCdPY8OpYW4sIDQwNTUwIEzDqW9uLCBGcmFuY2U', '43.8747919', '-1.3038105');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1047, null, 'Avenue Aristide Briand', '33600', 'Pessac', 'EixBdmVudWUgQXJpc3RpZGUgQnJpYW5kLCAzMzYwMCBQZXNzYWMsIEZyYW5jZQ', '44.7984431', '-0.6286113');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1048, '25', 'Rue du Mail', '38500', 'Voiron', 'ChIJ6frnPTnkikcR2fJBkj3GYsA', '45.3639015', '5.59143839999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1049, '2', 'Rue de Saint-Estèphe', '33600', 'Pessac', 'ChIJtc-WLArZVA0RzdNcVVXEFR0', '44.8089939', '-0.6539367');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1050, '6', 'RIEUFLAGET', '33790', 'ST ANTOINE DU QUEYRET', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1051, '7', 'penot', '33490', 'PIAN SUR GARONNE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1052, '7', 'rue Fustel de Coulanges, Domaine de Teynac', '33700', 'MERIGNAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1053, '4', 'Rue Saint Adrien', '13008', 'Marseille', 'ChIJlVgsjazAyRIRrB6Guoq_0VY', '43.2819773', '5.38742179999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1054, '7', 'rue de lys', '24000', 'PERIGUEUX', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1055, '8 bis', 'rue jules delaube', '33160', 'SAINT MEDARD', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1056, '1', 'rue Louis Lagogette, Immeuble Aalta 3éme étage', '33150', 'CENON', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1057, '15', 'Rue Bellevue', '33600', 'Pessac', 'ChIJZ7n7JhbZVA0R19aEkPKRKDU', '44.7926963', '-0.6519859');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1058, null, null, '33', 'BELLIN BELIER', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1059, null, null, '33380', 'MIOS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1060, '45', 'lot Le Piron', '33670', 'SADIRAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1061, null, 'Av Aristide Briand', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1062, '94', 'av du General Leclerc', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1063, '13', 'Allée Camille Saint-Saëns', '33114', 'Le Barp', 'ChIJbd67AEXvVA0R9dQ-iEuIpNo', '44.6114007', '-0.7651104');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1064, null, null, '33700', 'MERIGNAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1065, '7', 'Rue François Mauriac', '33140', 'Villenave-d''Ornon', 'ChIJwQexv7AgVQ0RBjsPgYGB7kU', '44.7658104999999', '-0.588351');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1066, '10', 'Rue de la Mirante', '33600', 'Pessac', 'ChIJNd0avGTZVA0RI2Pwae_ZzQc', '44.8008592', '-0.6717016');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1067, '58', 'av montesquieu', '33240', 'SAINT ANDE DE CUBZAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1068, '7', 'Impasse Rivelaine', '33710', 'GAURIAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1069, '16', 'route de la mairie', '33710', 'BAYON SUR GIRONDE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1070, '5', 'route des cotes de Bourg', '33710', 'BAYON SUR GIRONDE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1071, '13', 'Bayens', '33570', 'PUISSEGUIN', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1072, '2', 'marquey sud', '33330', 'SAINT EMILLION', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1073, '10', 'Avenue de Villemejan', '33600', 'Pessac', 'ChIJ2YVGe5nYVA0RC4flrG2NwpI', '44.7971012', '-0.6080304');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1074, '3', 'impasse des genets', '17130', 'SOUMERAS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1075, null, null, '33620', 'MARSAS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1076, '58', 'av de montesquieu', '33240', 'SAINT ANDRE DE CUBZAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1077, '68', 'av de surcouf', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1078, '2', 'Mail Pierre Mendès-France', '33600', 'Pessac', 'ChIJw3z-C_jYVA0RQX61KVG6uNU', '44.8110985', '-0.630789199999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1079, '6', 'Allée des Asphodèles', '33610', 'Canéjan', 'ChIJzR7MScbeVA0Rl2kHQB7nXiw', '44.7631726', '-0.655535');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1080, '47', 'Route de l''Estuaire', '33390', 'Plassac', 'ChIJwauV_KjTAUgRQs1FM_Y8YOk', '45.1029897', '-0.6446038');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1081, '92', 'rue chantecrit', '33000', 'BORDEAUX Chartrons', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1082, '34', 'Avenue Descartes', '33167', 'SAINT MEDARD EN JALLES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1083, '11', 'Avenue Henri Barbusse', '33700', 'Mérignac', 'ChIJkxhyr3nXVA0Ra2VReNC9kB0', '44.8560767999999', '-0.642203');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1084, '15', 'Rue de la Croix de Monjous', '33170', 'Gradignan', 'ChIJgzTGparYVA0RxRx6pxM-lno', '44.7747539', '-0.6018319');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1085, '1 bis', 'rue jean de la fontaine', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1086, '16', 'Rue Igor Stravinsky', '33160', 'Saint-Médard-en-Jalles', 'ChIJRa2uHyHOVA0R5XfHEkYBMQU', '44.9007792', '-0.755787299999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1087, '87', 'Cours de la Somme', '33800', 'Bordeaux', 'ChIJ9US3ZbcnVQ0RkratFQLcrDE', '44.8272743', '-0.572593599999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1088, null, 'chemin de la gaillarde', '33710', 'TEUILLAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1089, '31', 'Rue Gutenberg', '33400', 'Talence', 'ChIJsfqYPIEnVQ0RqgUcZwuZ1Wo', '44.8153269', '-0.5984313');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1090, '52', 'Allée du Passage Douen', '33370', 'Bonnetan', 'ChIJJW-QmU46VQ0R9xETWLffaQU', '44.8175737', '-0.3998118');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1091, '17', 'Allée des Fougères', '33240', 'Saint-André-de-Cubzac', 'ChIJ-fTF8_AnAEgRc_5kM98UYWM', '45.0057518', '-0.4394824');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1092, '59', 'rue de la cassadotte', '33450', 'IZON', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1093, '10C', 'Rue Alexis Puyo', '33160', 'Saint-Médard-en-Jalles', 'ChIJw9OQO8bRVA0RJFDiATjGbY8', '44.8957060999999', '-0.737484999999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1094, '2', 'Chemin de Teyche', '33480', 'Castelnau-de-Médoc', 'ChIJ3VVmWfnYAUgRCLlyBp7ljKc', '45.0290894', '-0.796696699999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1095, '8', 'Palus', '33210', 'Coimères', 'ChIJLwszAWtxVQ0RqMgKdVBzzx0', '44.4961154999999', '-0.2078579');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1096, '18', 'Avenue Gustave Eiffel', '33600', 'Pessac', 'ChIJ45YlDSXZVA0RYkdbYdts-gE', '44.7845431', '-0.646724199999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1097, null, null, '33000', 'BISCAROSSE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1098, '1', 'lieu dit le hageot', '33410', 'CARDAN', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1099, '10C', 'Rue Alexis Puyo', '33160', 'Saint-Médard-en-Jalles', 'ChIJw9OQO8bRVA0RJFDiATjGbY8', '44.8957060999999', '-0.737484999999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1100, null, 'Talon', '17360', 'SAINT MARTIN DE COUX', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1101, '3', 'la Guillade', '33920', 'CIVRAC DE BLAYE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1102, '61', 'cours Saint Louis', '33000', 'BORDEAUX', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1103, '9', 'Rue des Poilus', '33600', 'Pessac', 'ChIJlbvxSPrYVA0RmygytIsez5w', '44.80534', '-0.6317678');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1105, '17', 'rue de la Tourasse', '33750', 'Saint Quentin de Baron', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1106, '110', 'Avenue du Peyrou', '33370', 'Artigues-près-Bordeaux', 'ChIJny-RYA0vVQ0RMPQFIJT3810', '44.869736', '-0.4967164');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1107, '129', 'rue jules Guesde, résidence monte cristo', '33270', 'FLOIRAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1108, '18', 'chemin de Paguemaou', '33360', 'CAMBLANES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1109, '10 bis', 'place de l''église', '33920', 'SAINT CHRISTOLY DE BLAYE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1110, '50', 'Rue de la Lande', '33240', 'Saint-Gervais', 'ChIJFRI-tRIoAEgRuRS1G84FNeo', '45.0177102', '-0.4607203');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1111, '16', 'Route de Lenan', '33138', 'Lanton', 'ChIJAzZ1fWi9VA0R5HwUVeQsLwQ', '44.7057499999999', '-1.0371439');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1112, '110', 'Avenue du Peyrou', '33370', 'Artigues-près-Bordeaux', 'ChIJny-RYA0vVQ0RMPQFIJT3810', '44.869736', '-0.4967164');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1113, null, 'Résidence Rosiers Bellevue A2', '33170', 'GRADIGNAN', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1114, null, null, '33', 'EYSINES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1115, null, 'Chateau Blanzac', '33350', 'SAINT MAGNE DE CASTILLON', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1116, '10', 'route du chateau d''eau', '33390', 'PLASSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1117, '63', 'route de germignan', '33160', 'SAINT AUBIN DU MEDOC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1118, null, 'Chemin bremontier', '33880', 'CAMBES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1119, '3', 'rue de la Hortie', '33240', 'SAINT GERMAIN DE LA RIVIERE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1120, '90', 'route de Coirac', '33540', 'GORNAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1121, null, 'BP 40', '33034', 'BORDEAUX Cedex', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1122, '13 bis', 'avenue Aristide Briand', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1123, null, null, '33170', 'SAIN MEDARD', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1124, '2AA', 'LA NAUZE', '33580', 'SAINT FERME', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1125, '9', 'rue des glycines', '33112', 'SAINT LAURENT DU MEDOC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1126, '6', 'rue ferdinand Lafargue', '33780', 'SOULAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1127, '5', 'Rue de la Paix', '33150', 'Cenon', 'ChIJI-m1llUvVQ0Rm1VO5wqmNsA', '44.8502502', '-0.522603399999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1128, null, 'Rue des huttiers', '33980', 'AUDENGE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1129, '4', 'rue Amiral Courbet', '33740', 'ARES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1131, '106', 'route des graves', '33640', 'PORTETS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1132, '17', 'Rue des Pavillons', '33600', 'Pessac', 'ChIJydTQqz7ZVA0Rp-EPyCAFgrY', '44.788106', '-0.6537682');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1133, '119', 'Rue Jean Goujon', '33160', 'Saint-Médard-en-Jalles', 'ChIJu1DJ3fPQVA0RrGH_w57yrJE', '44.8713893', '-0.709211199999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1134, '9', 'bis rue Francis Jammes', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1135, '174', 'avenue du Truc BP 60275', '33697', 'MERIGNAC Cedex', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1136, '108', 'Avenue Docteur Nancel Penard', '33600', 'Pessac', 'ChIJ2cGdK_nYVA0RiLMPOXexjk4', '44.8089298999999', '-0.634412');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1137, '1', 'chez Dehors', '17270', 'NEUVICQ', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1138, '202', 'Avenue Pasteur', '33600', 'Pessac', 'ChIJG-YtOQXZVA0RsoSAZ4oCaxU', '44.8025388999999', '-0.647554199999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1139, null, 'Avenue Aristide Briand', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1140, '15', 'rue des Vignobles', '33240', 'SAINT ROMAIN LA VIREE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1142, null, 'rue Emile Zola', '33000', 'BORDEAUX', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1143, '80', 'Rue du Montalieu', '33320', 'Eysines', 'ChIJuwgjZCPXVA0R9B00KAg_ebs', '44.8781815', '-0.6626928');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1144, '15', 'rue fouineyre', '33290', 'Luçon médoc', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1145, '15', 'résidence Edouard Dorc', '33390', 'BLAYE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1147, '251', 'Avenue de la Marne', '33700', 'Mérignac', 'Ei8yNTEgQXZlbnVlIGRlIGxhIE1hcm5lLCAzMzcwMCBNw6lyaWduYWMsIEZyYW5jZQ', '44.8326907999999', '-0.6453367');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1148, '1', 'Rue Gallieni', '33780', 'Soulac-sur-Mer', 'ChIJXc7eq36EAUgRb05-Im_JLIg', '45.5151979', '-1.1216442');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1149, null, null, '33140', 'VILLENAVE D''ORNON', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1150, null, 'Lieu dit GAVES, Laroque', '33410', 'CADILLAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1151, '173', 'Avenue Jean Cordier', '33600', 'Pessac', 'ChIJBd9IdGXYVA0Rk35UqRfCSsY', '44.819868', '-0.613134899999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1152, null, 'Chateau la Baronnerie', '33620', 'CEZAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1153, '31', 'Avenue André Lafon', '33820', 'Saint-Ciers-sur-Gironde', 'ChIJGwio4KzKAUgRMRPbmYe83XU', '45.2909865', '-0.6088446');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1154, '8', 'hERV2', '33920', 'SAINT CHRISTOLY DE BLAYE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1155, '20', 'rue de romainville', '33700', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1156, '10', 'Allée Ronsard', '33600', 'Pessac', 'ChIJXXIQLh3ZVA0RHXnqUcm8syA', '44.8016738', '-0.6408891');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1157, '14', 'bis route de lucrabey', '33250', 'CYSSAC MEDOC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1158, null, 'Les terres d''Abzac, lieu dit Petit Piron', '33230', 'ABZAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1159, null, 'Les Ourmes', '33990', 'HOURTIN', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1160, null, 'Allée de niki', '33160', 'SAINT MEDARD', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1161, null, 'Allée de niki', '33160', 'SAINT MEDARD', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1162, null, 'allée de niki', '33160', 'SAINT MEDARD', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1163, '91', 'Rue Principale', '33820', 'Étauliers', 'ChIJr6rV1YM0AEgRXwaBWJUbbUM', '45.2255225', '-0.5733444');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1164, '38', 'Avenue du Luxembourg', '33700', 'Mérignac', 'ChIJJ5OMQYXZVA0RnZEJzkFyKTw', '44.8197471', '-0.6688523');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1165, '11', 'chez le maure', '17210', 'ORIGNOLLES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1166, '18', 'Rue Pascal Mothes', '33800', 'Bordeaux', 'ChIJ7x3vw7AnVQ0RDf4gDjW4gMw', '44.824573', '-0.5716356');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1167, '24 bis', 'rue Antoune', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1168, '16', 'Rue Vincent Van Gogh', '33650', 'Saint-Médard-d''Eyrans', 'ChIJo9b7ryIiVQ0RuWA08sBz5eg', '44.7190551', '-0.5172445');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1169, '11', 'av Louis Barthou', '33000', 'BORDEAUX', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1170, '35', 'route du lavoir', '33710', 'COMPS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1171, '1', 'butte des juins', '33390', 'BERSON', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1172, '2', 'lotissement bicou', '33240', 'SALIGNAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1173, '7', 'Rue de l''Espérance', '33930', 'Vendays-Montalivet', 'ChIJ--scFbOOAUgRpHDrOURb0cs', '45.3815954999999', '-1.1493991');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1174, '9', 'rue des chasselas', '33180', 'SAINT ESTEPHE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1175, '12', 'rue de la gare', '33299', 'LUDON MEDOC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1176, '21', 'Rue de Brazza', '33700', 'Mérignac', 'ChIJjwgWjc3ZVA0RHNolLk1f3xI', '44.8387284999999', '-0.6429117');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1177, '140', 'rue des pinsons', '40', 'BISCAROSSE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1178, '100', 'rte de coutras', '33910', 'SAINT DENIS DE PILE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1179, '23', 'Impasse Nougueyrau', '33450', 'Izon', 'ChIJSYcTWIU2VQ0RySjWptwl6Nc', '44.9155261', '-0.345946');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1180, '2', 'Rue Saint-Denis', '86000', 'Poitiers', 'ChIJR36woXq-_UcRUVDwrtAE0XQ', '46.5842748', '0.3466294');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1181, '1', 'route des salmondieres', '86800', 'JARDRES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1182, '372', 'chemin de pillon', '33880', 'BAURECH', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1183, '6', 'Rue André Clerc', '33390', 'Saint-Martin-Lacaussade', 'ChIJ22yc0WXSAUgR9sVp88nhn1g', '45.1340297', '-0.6499021');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1184, '1', 'chemin du Maine de Laborde', '33450', 'SAINT LOUBES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1185, '1', 'chemin du Maine de laborde', '33450', 'SAINT LOUBES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1186, '61', 'Route du Tasta', '33450', 'Saint-Sulpice-et-Cameyrac', 'ChIJV8uLw7Y2VQ0RAL6xTXiFHGw', '44.9098444', '-0.3685681');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1187, '230', 'Route de Libourne', '33240', 'Saint-André-de-Cubzac', 'ChIJ21f8TcgyVQ0R7JbY2tFbyrM', '44.9924052', '-0.4292378');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1188, '64 bis', 'Av Louis Didier', '33240', 'LIBOURNE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1189, null, 'Lieu dit bras de fer', '33920', 'CIVRAC DE BLAYE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1190, '9', 'chemin duburdieu', '33610', 'CESTAS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1191, '3801', 'route de Dax', '40350', 'POUILLON', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1192, '57', 'rue de balzac', '33000', 'TALENCE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1193, '8', 'rue de l''école', '33240', 'SAINT GEES DE FRONSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1194, '1', 'jartot', '33620', 'LARUSCADE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1195, '20', 'Rue de Metz', '33000', 'Bordeaux', 'ChIJu6QDLfcnVQ0RY2Axp7zf3n4', '44.8377499', '-0.596859199999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1196, '34', 'Chemin de Tarreyrots', '33240', 'Salignac', 'ChIJw55QTrIgAEgRPnSTCgQeCDg', '45.0106531', '-0.3719157');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1197, '12', 'avenue de Verdun', '33480', 'MIOS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1198, '110', 'Avenue du Peyrou', '33370', 'Artigues-près-Bordeaux', 'ChIJny-RYA0vVQ0RMPQFIJT3810', '44.869736', '-0.4967164');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1199, null, null, '33600', 'Pessac', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1200, '50', 'rue Valentin Bernard', '33710', 'Bourg sur Gironde', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1201, null, 'Rue de Gascogne', '33160', 'Saint medard en jalles', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1202, '25', 'av Bel Air', '33000', 'BORDEAUX', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1203, '1éA', '12A av de Verdun', '33380', 'MIOS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1204, '1', 'Chemin des Collines', '33270', 'Bouliac', 'ChIJ4-Jvn0okVQ0Rv7HnlhuM6fM', '44.8109858', '-0.5065225');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1205, '15', 'rue du Bosquet de Venteille', '33185', 'LE HAILLAN', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1206, '70', 'chemin du broutey', '33240', 'SAINT ROMAIN LA VIREE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1207, '2', 'Avenue Cassiopée', '33160', 'Saint-Médard-en-Jalles', 'ChIJYUCpFozQVA0Rbz7U6_7n3cU', '44.8632465', '-0.7096135');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1208, '21', 'Rue de Catros', '33000', 'Bordeaux', 'ChIJZ3sPqgwoVQ0Rz4bputXV174', '44.8537706', '-0.5827934');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1209, '47', 'Route de Coutras', '24700', 'Le Pizou', 'ChIJu40T-Rb__0cR4csOlKnUxlo', '45.0252551', '0.0535004');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1210, '4', 'barail des robins', '33920', 'SAINT GIRON D''AIGUEVIVES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1211, '10', 'rue Gabriel Faure', '33000', 'EYSINES', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1212, '30', 'Rue Xaintrailles', '33000', 'Bordeaux', 'ChIJP8TLx5InVQ0Rco30ZETSUgE', '44.8295671', '-0.590852199999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1213, null, 'Lieu dit GAVES LAROQUE CADILLAC', '33410', 'CADILLAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1214, '1 bis', 'route de la vallée', '33670', 'CURSAN', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1216, '34', 'l''oiseau', '33126', 'FRONSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1217, '5', 'allée des pensées', '33', 'LANTON', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1218, '82', 'Avenue de Magonty', '33600', 'Pessac', 'ChIJ15Rzkr7bVA0RqDKBeWr_Abk', '44.7951915', '-0.7000539');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1219, '26', 'Rue des Frères Lumière', '33560', 'Carbon-Blanc', 'ChIJqUoRjIcuVQ0Rfwfaos1eOWc', '44.9167838', '-0.4883448');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1220, '6', 'rue Dansperre', '33720', 'VERLADE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1221, '53 bis', 'route du liard', '33340', 'SAINT GERMAIN D''ESTEUIL', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1222, '1', 'route lassalle', '33930', 'VENDAYS MONTALIVET', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1223, '18', 'Rue de Leyssaut', '33990', 'Hourtin', 'ChIJRcdsiyPwAUgRw_x9T0nvffo', '45.167617', '-1.0711315');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1224, '52', 'passage du jeune', '33780', 'SOULAC SUR MER', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1225, null, 'ZA DU BEDAT', '33650', 'ST MEDARD D’EYRANS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1226, null, null, '33000', 'SAINT JEAN D''ILLAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1227, '3', 'allee des pensées', '33000', 'LANTON', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1228, '15', 'Avenue Johann Strauss', '33510', 'Andernos-les-Bains', 'ChIJDwYFXxijVA0RZMZ2yLg1l1Y', '44.7402312', '-1.0790043');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1229, '17', 'domain de de castelnau', '33490', 'SAINT PIERRE D''AURILLAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1230, '95', 'Avenue Léon Blum', '33110', 'Le Bouscat', 'ChIJJQDvLNzXVA0Rc508dWrkoZY', '44.870009', '-0.6063777');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1231, '36', 'avenue Jean Luc Vonderheyden', '33460', 'ARSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1232, '11', 'les grands regniers', '33220', 'EVNESSE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1233, null, 'Contrelaoude', '33990', 'HOURTIN', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1234, '8', 'Rue Ulysse Gayon', '33000', 'Bordeaux', 'ChIJPUPQ9QgoVQ0RMSHjmaH_tSw', '44.851675', '-0.590403799999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1235, '7', 'Rue Emile Dreux', '33200', 'Bordeaux', 'ChIJoT2dg_vXVA0RJG2qCUwcpJ8', '44.8557085', '-0.606644699999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1236, '58', 'route de Bordeaux', '33220', 'PORT SAINTE FOY', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1237, '46', 'Rue Théodore Ducos', '33000', 'Bordeaux', 'ChIJ-9GZ_r8nVQ0RmAoS8Y3djVk', '44.8299844999999', '-0.5824287');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1238, null, 'Av Robert Schumann', '33600', 'PESSAC', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1239, '2', 'rue Descartes', '33000', 'VILLENAVE', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1240, '3', 'résidence le chateau', '24700', 'LE PIZOU', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1241, '504', 'Rue Voltaire', '33290', 'Le Pian-Médoc', 'ChIJk0bLGBfVVA0RfbFXSgUUvWw', '44.9762142', '-0.627822299999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1242, '37', 'Avenue de Brivazac', '33600', 'Pessac', 'ChIJI_50QYzYVA0Re9Iq7ZQGnpA', '44.8054413999999', '-0.617094099999999');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1243, '2', 'Place Deutsch de la Meurthe', '33170', 'Gradignan', 'ChIJqcYQtLXYVA0RJ3dVzN53Z_A', '44.7772469', '-0.6183012');
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1244, '3', 'Rue haute', '25870', 'AUXONS DESSOUS', null, null, null);
insert into adresse(id, numero, voie, code_postal, commune, place_id, latitude, longitude) values (1245, '1', 'place barbey vieux', '33640', 'ARBANATS', null, null, null);

insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1000, 'Mme', 'LAPELLEGERIE Christelle', null, null, 'christellelapellegerie@yahoo.fr',1000);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1001, 'Mr', 'FAUVET Jérome', '0553242323', null, 'jerome.fauvet@cobatri.com',1001);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1002, 'MrMme', 'BISSERIEX', null, null, null,1002);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1003, 'MrMme', 'DESCORPS', null, '0619762986', 'descorps@free.fr',1003);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1004, 'Mr', 'BAYARD', '0556364635', '0675358977', null,1004);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1005, 'Mr', 'ALBINET', null, '0624057844', null,1005);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1006, 'Mr', 'CHARLES', null, '0618704139', 'contact@mc-charles.fr',1006);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1007, 'MrMme', 'FAURE', null, null, null,1007);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1008, 'MrMme', 'HOYAUX', '0556463208', null, 'andre-frederic.hoyaux@laposte.net',1008);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1009, 'Mr', 'CHAUVET Thierry', null, '0672132313', null,1009);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1010, 'MrMme', 'BILLIF', null, '0677029754', 'fabricebaillif@aol.com',1010);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1011, 'MrMme', 'MONJALON', null, '0663081619', 'thomas@monjalon.net',1011);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1013, 'Mme', 'CHAILLAT', '0556365365', null, null,1013);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1014, 'Mr', 'CASSELEUX', null, '0614620357', 'jeremie.casseleux@gmail.com',1014);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1015, 'Mr', 'DEQUEVAUVILLER', null, null, null,1015);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1016, 'MrMme', 'SIMON', null, null, 'lorensimaison@gmail.com',1016);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1017, 'Mr', 'ROUSSARIE', null, null, 'jean-louis.roussarie@wanadoo.fr',1017);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1018, 'Mr', 'URGIN Nicolas', null, '0663051062', 'nicolas.urgin@free.fr',1018);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1019, 'Mr', 'ORENSANZ', null, '0681941935', 'orensanz.g@orange.fr',1019);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1020, null, null, '0549940727', null, null,1020);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1021, 'Mr', 'PESNEAU', null, '0622606276', 'corentin.pesneau@gmail.com',1021);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1022, 'Mr', 'LANGLOIS Jean-Pierre', null, '0630378771', 'jeanpierre.langlois@orange.fr',1022);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1024, 'Mr', 'CELHAY', null, '0686929624', null,1024);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1025, 'Mr', 'CEBEILLAC', null, null, null,1025);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1026, 'Mr', 'MEYNET', '0556214720', null, 'Meynetlydie@hotmail.fr',1026);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1027, 'Mr', 'LASNIER', null, null, null,1027);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1028, 'Mr', 'PAGE', null, '0617136702', 'racheldona2107@gmail.com',1028);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1029, 'Mr', 'LESTEL', null, '0620224227', 'nadia.lestel@sfr.fr',1029);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1030, 'Mr', 'NICOLAS GARDAT', null, '0671195700', 'nicolas.gardrat@wanadoo.fr',1030);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1031, 'Mr', 'MAROILAN', null, '0608288907', 'a.mariolan@orange.fr',1031);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1032, 'Mr', 'POUJARDIEU', null, '0645735704', 'poujardieu.isabelle@orange.fr',1032);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1033, 'Mr', 'MARCHE', '0556967903', null, null,1033);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1034, 'Mr', 'BOUDIGUES', null, '0617084386', 'ntena@free.fr',1034);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1035, 'Mr', 'SCHON', '0553820838', null, 'colettedoudou@hotmail.fr',1035);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1036, 'MrMme', 'COCHET', null, null, 'marjolaine.fabriol@mageos.com',1036);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1037, 'Mme', 'MOYA', null, null, 'Marie.moya@sfr.fr',1037);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1038, 'Mr', 'DUCLOS', null, null, null,1038);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1039, 'Mr', 'GAUTHIER', null, null, null,1039);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1040, 'Mme', 'ROCHEGALUES', null, null, null,1040);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1041, 'Mr', 'GAUTIER', null, null, 'michele.gautier33@gmail.com',1041);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1042, 'Mme', 'PETIBOIS', null, null, null,1042);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1043, 'Mr', 'TRESSOL Paul', null, null, null,1043);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1044, 'Mr', 'CALIOT', null, null, null,1044);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1045, 'Mr', 'DOS SANTOS Nicolas', null, '0665774029', 'sarldsjetfils@orange.fr',1045);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1046, 'Mme', 'ROCHEGALVES', null, null, null,1046);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1047, 'Mme', 'BIDEGARAY Nicole', null, null, 'nicolebidegaray@yahoo.fr',1047);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1048, 'Mme', 'PIGACHE', null, null, null,1048);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1049, 'Mme', 'LEVEQUE', null, null, null,1049);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1050, 'Mr', 'ROUBEAU', null, '0678452562', null,1050);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1051, 'Mr', 'LAMARQUE & FAURE', null, '0661231477', 'arianelam@hotmail.fr',1051);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1052, 'Mr', 'LEILA', null, '0608953744', 'alex.guenegou@wanadoo.fr',1052);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1053, 'Mr', 'AMANIEU', null, null, null,1053);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1054, null, null, null, '0668461111', 'lmceurl@gmail.com',1054);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1055, 'MrMme', 'VERDERY', '0556059756', null, null,1055);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1056, null, null, null, '0634238161', null,1056);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1057, 'MrMme', 'BILLON', null, null, null,1057);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1058, 'MrMme', 'DUDON et BLANC', null, null, 'blanc.nathalie@laposte.net',1058);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1059, 'MrMme', 'DUDON', null, null, 'sylviedudon@hotmail.fr',1059);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1060, 'Mr', 'EXCOFFON Yoann', null, '0659534328', 'yoyo64700@hotmail.com',1060);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1061, 'MrMme', 'CHABRAT', null, null, 'kimera94@yahoo.fr',1061);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1062, 'Mme', 'PLAUD', null, '0622793242', null,1062);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1063, 'MrMme', 'LE CLAINDRE et MERCADIER', null, '0663147788', null,1063);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1064, 'Mr', 'GUICHARD', null, null, 'vincentguichard123@gmail.com',1064);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1065, 'Mr', 'CHRISTOPHE', null, '0699490123', 'kitoff33@live.fr',1065);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1066, 'Mr', 'DELOR', null, null, null,1066);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1067, 'Mme', 'PIROUE', null, '0627717271', null,1067);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1068, 'MrMme', 'HARDOUIN', null, '0659832040', null,1068);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1069, 'Mr', 'FERMI BERNARD', '0557648983', null, null,1069);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1070, 'Mr', 'CEBEILLAC', null, null, null,1070);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1071, 'Mr', 'WOLF Julien', null, null, null,1071);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1072, 'Mr', 'BOUQUEY Bruno', null, null, null,1072);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1073, 'Melle', 'KALMOUNI', null, null, null,1073);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1074, 'Mr', 'CHERY', null, null, null,1074);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1075, 'Mr', 'PITAULT', null, '0685457823', null,1075);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1076, 'Mr', 'PIROUE', null, '0627717271', null,1076);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1077, 'Mr', 'LEONARD', null, null, null,1077);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1078, 'Mr', 'HOSTEIN Jean-Louis', null, null, null,1078);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1079, 'Mr', 'PILLOT Damien', null, '0662476417', 'damien.pillot@gmail.com',1079);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1080, 'Mr', 'RAZAFINDRAHAINGO Alexandre', '0557684330', '0630539899', null,1080);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1081, 'Mme', 'GONZALEZ Coralie', null, null, 'gonzalezcoralie@hotmail.com',1081);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1082, null, null, null, '0556701570', null,1082);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1083, null, null, '0556021690', null, null,1083);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1084, 'Mr', 'LANGLOIS Xavier', null, null, 'xaviercecile@free.fr',1084);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1085, 'Mr', 'TORRIANI', '0556365143', null, null,1085);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1086, 'MrMme', 'GRENIER', null, '0688900091', null,1086);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1087, null, null, null, '0607491915', null,1087);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1088, 'Mr', 'GITTON', null, null, null,1088);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1089, 'Mme', 'NOUZEILLES', null, null, null,1089);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1090, 'Mr', 'FOUCHE', null, null, 'Veronique.Geneste@caissedesdepots.fr',1090);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1091, 'Mr', 'BORDESSOULES', null, null, null,1091);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1092, 'Mr', 'BEAUQUIS / RENAUD-LYAT', null, null, null,1092);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1093, 'MrMme', 'COTARD', null, '0633716267', null,1093);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1094, 'Mr', 'DUFIN', null, '0678269127', null,1094);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1095, 'Mr', 'DALLAVALLE', '0953535610', '0631527316', null,1095);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1096, 'Mme', 'FINANSO France', '0972422908', null, null,1096);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1097, 'Mr', 'BOUZIGE', '0608929600', '0684418066', null,1097);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1098, 'Mr', 'AZNAR Victor', null, '0624352067', null,1098);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1099, 'MrMme', 'CHOTARD', null, null, null,1099);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1100, 'Mr', 'TESSIER Michel', '0546042191', null, null,1100);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1101, 'Mr', 'DECOUZON', null, '0608427726', null,1101);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1102, null, 'Nicolas-Gaston Ellie', null, '0686071285', null,1102);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1103, 'Mme', 'DELEST', null, null, null,1103);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1105, 'MrMme', 'DUTILLEUL Jonathan / DHELLIN Alexia', null, '0644018124', null,1105);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1106, null, null, null, null, null,1106);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1107, 'Mme', 'CAMOU JUNCAS Annie', null, null, null,1107);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1108, 'Mr', 'MARCADIER', null, null, null,1108);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1109, 'Mr', 'MARCHAND Philippe', '0557424695', null, null,1109);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1110, 'MrMme', 'MARCHAIS', null, null, null,1110);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1111, 'Mr', 'HARNIST Pascal', null, null, null,1111);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1112, null, null, null, null, null,1112);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1113, 'Mr', 'VALLE Batiste', null, '0661469112', null,1113);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1114, null, 'PRIE', null, null, null,1114);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1115, 'Mme', 'DANIELLE PONS', null, null, null,1115);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1116, null, 'LOVERDE', '0557420226', null, null,1116);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1117, null, 'LATORRE', null, null, null,1117);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1118, 'Mme', 'L''EGLISE', null, null, null,1118);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1119, null, 'THIBAUD', null, null, null,1119);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1120, null, 'LAMOUROUX', null, '0622447578', null,1120);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1121, null, null, null, null, null,1121);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1122, 'Mr', 'COCHET Antoine', null, null, null,1122);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1123, null, 'ROUX', null, null, null,1123);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1124, null, null, null, null, null,1124);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1125, null, 'BESTES LARROQUE', null, '0673014607', null,1125);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1126, null, null, null, null, null,1126);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1127, null, null, null, '0631034943', 'christophehardy.lmba@wanadoo.fr',1127);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1128, 'MrMme', 'GARLOPEAU / RUIZ ', null, null, null,1128);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1129, 'Mme', 'PEKKERIN Noëlle', null, '0642957627', null,1129);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1131, 'MrMme', 'DELBREL', null, '0609229196', null,1131);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1132, null, 'REYDON', null, '0661483366', null,1132);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1133, null, 'PRENEUX', null, '0631371547', null,1133);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1134, 'Mme', 'VEZIN Sandra', null, '0684897608', null,1134);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1135, null, null, null, '0556124141', null,1135);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1136, 'MrMme', 'BUFFARD', null, null, null,1136);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1137, 'Mr', 'BERGERON Fabrice', null, '0687238555', null,1137);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1138, 'Mr', 'COUVREUR Didier', null, null, null,1138);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1139, 'MrMme', 'CABROL', null, null, null,1139);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1140, null, 'MOCQUILLON', null, null, null,1140);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1142, null, 'SERINDAT / BERTON', '0664485232/0637669133', null, null,1142);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1143, 'Mr', 'BOSQ Bruno', null, '0786014720', null,1143);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1144, null, 'Ferreira Dias', null, '0760073108', 'dilma_87_lol@hotmail.com',1144);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1145, null, 'SAJANT', null, null, null,1145);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1147, 'MrMme', 'GOGUET', null, '0618512847', null,1147);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1148, null, null, '0961270735', null, 'sarl.dubouilh@wanadoo.fr',1148);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1149, 'Mr', 'ELIAS Vincent', null, null, null,1149);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1150, 'MrMme', 'VENDRASCO', null, '0680584136', null,1150);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1151, null, 'ALBERTINI', null, null, 'thibault.albertini@orange.fr',1151);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1152, 'MrMme', 'DEYZAC', null, null, null,1152);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1153, 'Mr', 'DIAS Alain', '0557327592', '0669158975', null,1153);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1154, 'Mr', 'FOUCHET Alain', '0557425823', '0667189264', null,1154);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1155, 'Mr', 'LE GALL', null, null, null,1155);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1156, 'Mr', 'PANCHEVRE', null, null, null,1156);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1157, null, 'ROJO', null, '0611321998', null,1157);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1158, null, 'BEZIES', null, '0614901579', null,1158);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1159, null, 'BERJAL', null, '0772910929', null,1159);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1160, null, 'URBANO', '0670233276', '0699024627', null,1160);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1161, null, 'GABRIEL / SERRE', null, '0626269883', null,1161);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1162, null, 'ARZILLER / CINUS', '0670233276', '0699024627', null,1162);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1163, null, null, null, null, null,1163);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1164, null, 'FULCHIRON', null, '0695244834', 'Jimmyfb@yahho.fr',1164);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1165, 'Mr', 'AUDUBERTEAU Eric', null, '060317078', null,1165);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1166, null, null, null, null, null,1166);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1167, 'Mme', 'FOURNEREAU', null, '0685109935', null,1167);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1168, null, 'ETCHEBERYGARAY', '0556727754', null, null,1168);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1169, null, 'DURAND', null, '0675390400', null,1169);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1170, null, 'TOMASELA', null, '0615640176', null,1170);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1171, 'Mme', 'LEMELLE', null, '0608423520', null,1171);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1172, null, 'JAUBERT', null, '0665620701', null,1172);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1173, 'Mme', 'CAHILAU Julie', null, '0674877869', null,1173);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1174, null, 'PREVOT', null, '0604452978', null,1174);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1175, null, 'DUCAMP', null, '0612576504', null,1175);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1176, 'Mme', 'DUC', null, null, null,1176);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1177, 'Mr', 'CLAIROTTE', null, '0608269546', null,1177);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1178, 'Mr', 'MASSOT', '0557923236', null, null,1178);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1179, null, null, null, null, null,1179);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1180, null, null, null, '0781233045', null,1180);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1181, null, null, null, '0683804321', null,1181);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1182, 'MrMme', 'KOENIG', null, null, null,1182);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1183, 'Mr', 'PASQUES', null, '0626265181', null,1183);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1184, 'Mme', 'SABLE Lisa', null, '0644236826', null,1184);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1185, 'Mme', 'SABLE Estelle', null, null, null,1185);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1186, 'Mr', 'BLONDEL Nicolas', null, '0635490034', null,1186);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1187, null, null, '0557422613', '0651491373', null,1187);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1188, null, 'CASTAGNA', null, '0620582228', 'danielle.castagna@orange.fr',1188);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1189, 'Mr', 'DECOMBE', null, '0682204445', null,1189);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1190, 'Mr', 'CRESP', null, null, null,1190);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1191, 'Mme', 'DECLA', null, null, null,1191);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1192, 'Mme', 'DAUGUET Caroline', null, '0682131139', null,1192);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1193, 'Mme', 'MONBARBUT', null, '0686784463', null,1193);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1194, null, 'LARROUTUROU', null, '0683832563', null,1194);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1195, null, 'CARON', null, '0607164656', null,1195);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1196, 'Mr', 'AUDINETTE', null, '0627473457', null,1196);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1197, 'Mr', 'ROUSSEAU', null, null, null,1197);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1198, null, null, null, null, null,1198);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1199, null, 'SIRIEX', null, null, 'Siriex33600@gmail.com',1199);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1200, 'Mme', 'BERNARD', '0557682871', null, null,1200);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1201, 'Mr', 'BRUNE BARBE', null, null, null,1201);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1202, null, 'BANOS', null, null, null,1202);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1203, null, 'ROUSSEAUX', null, null, null,1203);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1204, 'Mme', 'FAVIER', null, null, null,1204);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1205, 'Mr', 'DELGADO', '0556027570', null, null,1205);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1206, 'Mme', 'PASSEREAU', null, '0662290243', null,1206);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1207, null, 'BEYNEL', null, null, 'p.beynel@orange.fr',1207);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1208, 'Mr', 'LARAN', null, null, null,1208);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1209, null, 'TERRYN', null, '0670160852', 'dominique-terryn@orange.fr',1209);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1210, 'Mr', 'VIEN', null, '0631442962', null,1210);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1211, 'MrMme', 'JAILLET', null, '0662749446', 'leonore.jaillet@gmail.com',1211);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1212, 'Mme', 'LEJET', null, '0660269489', 'vlm47@orange.fr',1212);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1213, 'Mme', 'PICOT', null, null, null,1213);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1214, 'Mr', 'SERCLERAT', null, '0674626424', null,1214);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1216, 'Mr', 'PENARD', null, '0609354169', null,1216);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1217, 'MrMme', 'PREVEAU', null, '0680446407', null,1217);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1218, 'MrMme', 'BELLOC', '0556071774', null, null,1218);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1219, null, null, null, null, null,1219);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1220, null, 'NGOUANDZI', null, null, null,1220);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1221, null, 'LUCEYRAN', null, '0676149993', null,1221);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1222, null, 'GALANT', null, '0671507595', null,1222);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1223, null, 'BARRET', null, '0671814243', null,1223);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1224, null, 'BASSIBEY', null, '0684509298', 'laurent.bassibey@gmail.com',1224);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1225, null, 'GIB CONSTRUCTION', '0557961242', null, null,1225);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1226, null, 'DARMAILLACQ', null, '0665157237', null,1226);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1227, null, 'BOURBON PALLAS', null, '0630726748', null,1227);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1228, null, 'PRIEUR', null, '0617308527', null,1228);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1229, 'Mr', 'THOUESNY', null, null, null,1229);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1230, 'Mr', 'SIERRA', null, null, null,1230);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1231, 'Mr', 'TAUZIER Florian', null, '0629757552', null,1231);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1232, 'Mr', 'BOS', null, '0610861529', null,1232);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1233, 'MrMme', 'GIRY', null, '0611157007', null,1233);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1234, 'Mr', 'DUPONT', null, '0672468096', null,1234);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1235, null, 'MERLET', null, '0627301413', null,1235);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1236, null, 'PARTEDIS', '0553242323', null, null,1236);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1237, 'Mme', 'CROCKETT Guylaine', null, null, null,1237);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1238, 'MrMme', 'STEVENS', null, null, null,1238);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1239, null, 'MIRAMONT', null, '0688726829', 'mirchristi@gmail.com',1239);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1240, null, 'DARRAS', null, '0686621094', null,1240);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1241, 'Mme', 'BON Sylvie', null, '0687567645', null,1241);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1242, null, 'NAU', null, '0614515321', 'plombimpact@gmail.com',1242);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1243, 'MrMme', 'REMY', null, '0662440008', null,1243);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1244, null, 'BORTOLIN', null, null, null,1244);
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (1245, 'Mme', 'TESSIER-GUY Delphine', null, null, null,1245);