
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', 'rue du Géneral Sarrail ', '33400', 'TALENCE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'LAPELLEGERIE Christelle', '', '', 'christellelapellegerie@yahoo.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '58', 'route de Bordeaux ', '33220', 'PORT DE SAINTE FOY');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'FAUVET Jérome', '0553242323', '', 'jerome.fauvet@cobatri.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '35', 'lotissement Saussus ', '33250', 'PAUILLAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'BISSERIEX', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '6', 'rue de Lyon ', '33700', 'MERIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'DESCORPS', '', '0619762986', 'descorps@free.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '4', 'rue de Belfort ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BAYARD', '0556364635', '0675358977', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '15', 'avenue Aristide Briand ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'ALBINET', '', '0624057844', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '6', 'avenue la grande haie ', '33540', 'SAUVETEERE DE GUYENNE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CHARLES', '', '0618704139', 'contact@mc-charles.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Avenue Aristide Briand ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'FAURE', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', 'rue Hector Berlioz ', '33400', 'TALENCE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'HOYAUX', '0556463208', '', 'andre-frederic.hoyaux@laposte.net',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '6', 'cité de chante oiseau ', '33920', 'SAINT CHRISTOLY DE BLAYE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CHAUVET Thierry', '', '0672132313', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '33', 'rue Marechal Gallieni ', '33200', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'BILLIF', '', '0677029754', 'fabricebaillif@aol.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '10', 'rue du merle ', '33700', 'MERIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'MONJALON', '', '0663081619', 'thomas@monjalon.net',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '', '');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'VONDERHEYDEN', '', '0667974389', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '24', 'rue Jacques Cartier ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'CHAILLAT', '0556365365', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '3', 'chemin du champ d''Auron ', '33133', 'GALGON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CASSELEUX', '', '0614620357', 'jeremie.casseleux@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '29', 'route de l''estuaire ', '33710', 'COMPS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DEQUEVAUVILLER', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '4', 'allée laennec ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'SIMON', '', '', 'lorensimaison@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '34 bis', 'La Croix ', '33710', 'BOURG');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'ROUSSARIE', '', '', 'jean-louis.roussarie@wanadoo.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'URGIN Nicolas', '', '0663051062', 'nicolas.urgin@free.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '14', 'caussette ', '33350', 'SAINT PEY DE CASTETS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'ORENSANZ', '', '0681941935', 'orensanz.g@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Lieu-dit La Pillaudiere ', '79200', 'LA CHAPELLE BERTRAND');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '0549940727', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '12', 'allée Jean Giraudoux ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'PESNEAU', '', '0622606276', 'corentin.pesneau@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', 'chemin aouguitche ', '33610', 'CESTAS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'LANGLOIS Jean-Pierre', '', '0630378771', 'jeanpierre.langlois@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '', 'CAP FERRET');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BITAR', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '9', ' rue Armand Roux ', '33180', 'VERTHEUIL');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CELHAY', '', '0686929624', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '5', ' route des cotes de bourg ', '33710', 'BAYON SUR GIRONDE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CEBEILLAC', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '36', ' allee des bruyeres ', '33127', 'ST JEAN D''ILLAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'MEYNET', '0556214720', '', 'Meynetlydie@hotmail.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '11', ' allée des cosmos ', '33170', 'GRADIGNAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'LASNIER', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Chemin de la gaillarde ', '33710', 'TEUILLAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'PAGE', '', '0617136702', 'racheldona2107@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' rue du 19 mars ', '33340', 'BLAIGNAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'LESTEL', '', '0620224227', 'nadia.lestel@sfr.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '9', ' le Moulin ', '33210', 'LEOGEATS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'NICOLAS GARDAT', '', '0671195700', 'nicolas.gardrat@wanadoo.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '360', ' avenue de Guyenne ', '40600', 'BISCAROSSE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'MAROILAN', '', '0608288907', 'a.mariolan@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '250', ' allée de piroulet ', '40600', 'BISCAROSSE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'POUJARDIEU', '', '0645735704', 'poujardieu.isabelle@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '155', ' rue Fernand Audeguil ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'MARCHE', '0556967903', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '39', ' rue Felix Faure ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BOUDIGUES', '', '0617084386', 'ntena@free.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '3', ' rue du bac ', '33230', 'SABLONS LES PEINTURES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'SCHON', '0553820838', '', 'colettedoudou@hotmail.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Avenue Aristide Briand ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'COCHET', '', '', 'marjolaine.fabriol@mageos.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '19', ' avenue aristide briand ', '33600', 'Pessac');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'MOYA', '', '', 'Marie.moya@sfr.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'rue de la princesse ', '33700', 'MERIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DUCLOS', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '19', ' rue Saint Jacques ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'GAUTHIER', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '40', ' avenue de l''ocean ', '40550', 'LEON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'ROCHEGALUES', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33', 'CESTAS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'GAUTIER', '', '', 'michele.gautier33@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '20', ' rue des villas ', '33200', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'PETIBOIS', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '41', ' rue val de bellassise ', '33560', 'SAINT EULALIE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'TRESSOL Paul', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '40600', 'BISCAROSSE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CALIOT', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', ' allée de la cantine ', '33830', 'BELLIN-BELIET');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DOS SANTOS Nicolas', '', '0665774029', 'sarldsjetfils@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '40', ' avenue de l''ocean ', '40550', 'LEON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'ROCHEGALVES', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'avenue aristide briand ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'BIDEGARAY Nicole', '', '', 'nicolebidegaray@yahoo.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '25', ' rue du Mail ', '38500', 'VOIRON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'PIGACHE', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2', ' rue Saint Estèphe ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'LEVEQUE', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '6', ' RIEUFLAGET ', '33790', 'ST ANTOINE DU QUEYRET');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'ROUBEAU', '', '0678452562', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', ' penot ', '33490', 'PIAN SUR GARONNE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'LAMARQUE & FAURE', '', '0661231477', 'arianelam@hotmail.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', ' rue Fustel de Coulanges, Domaine de Teynac ', '33700', 'MERIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'LEILA', '', '0608953744', 'alex.guenegou@wanadoo.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '4', ' rue saint adrien ', '13008', 'MARSEILLE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'AMANIEU', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', ' rue de lys ', '24000', 'PERIGUEUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '0668461111', 'lmceurl@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '8 bis', ' rue jules delaube ', '33160', 'SAINT MEDARD');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'VERDERY', '0556059756', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' rue  Louis Lagogette, Immeuble Aalta 3éme étage ', '33150', 'CENON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '0634238161', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '15', ' rue Bellevue ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'BILLON', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33', 'BELLIN BELIER');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'DUDON et BLANC', '', '', 'blanc.nathalie@laposte.net',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33380', 'MIOS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'DUDON', '', '', 'sylviedudon@hotmail.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '45', 'lot Le Piron ', '33670', 'SADIRAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'EXCOFFON Yoann', '', '0659534328', 'yoyo64700@hotmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Av Aristide Briand ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'CHABRAT', '', '', 'kimera94@yahoo.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '94', ' av du General Leclerc ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'PLAUD', '', '0622793242', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '13', ' allée Camille Saint Saens ', '33114', 'LE BARP');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'LE CLAINDRE et MERCADIER', '', '0663147788', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33700', 'MERIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'GUICHARD', '', '', 'vincentguichard123@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', ' rue Francois Mauriac ', '33140', 'VILLENAVE D''ORNON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CHRISTOPHE', '', '0699490123', 'kitoff33@live.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '10', ' rue de la Mirante ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DELOR', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '58', ' av montesquieu ', '33240', 'SAINT ANDE DE CUBZAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'PIROUE', '', '0627717271', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', ' Impasse Rivelaine ', '33710', 'GAURIAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'HARDOUIN', '', '0659832040', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '16', ' route de la mairie ', '33710', 'BAYON SUR GIRONDE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'FERMI BERNARD', '0557648983', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '5', ' route des cotes de Bourg ', '33710', 'BAYON SUR GIRONDE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CEBEILLAC', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '13', ' Bayens ', '33570', 'PUISSEGUIN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'WOLF Julien', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2', ' marquey sud ', '33330', 'SAINT EMILLION');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BOUQUEY Bruno', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '10', ' av Villemejean ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Melle', 'KALMOUNI', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '3', ' impasse des genets ', '17130', 'SOUMERAS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CHERY', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33620', 'MARSAS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'PITAULT', '', '0685457823', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '58', ' av de montesquieu ', '33240', 'SAINT ANDRE DE CUBZAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'PIROUE', '', '0627717271', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '68', ' av de surcouf ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'LEONARD', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2', ' Mail Pierre Mendès France ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'HOSTEIN Jean-Louis', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '6', ' allée des asphodelles ', '33610', 'CANEJAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'PILLOT Damien', '', '0662476417', 'damien.pillot@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '47', ' route de l''Estuaire ', '33390', 'PLASSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'RAZAFINDRAHAINGO Alexandre', '0557684330', '0630539899', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '92', ' rue chantecrit ', '33000', 'BORDEAUX Chartrons');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'GONZALEZ Coralie', '', '', 'gonzalezcoralie@hotmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '34', ' Avenue Descartes ', '33167', 'SAINT MEDARD EN JALLES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '0556701570', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '11', ' Av Henri Barbusse ', '33700', 'MERIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '0556021690', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '15', ' r Croix de Monjous ', '33170', 'GRADIGNAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'LANGLOIS Xavier', '', '', 'xaviercecile@free.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1 bis', ' rue jean de la fontaine ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'TORRIANI', '0556365143', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '16', ' rue Igar Stavinsky ', '33160', 'SAINT MEDARD EN JALLES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'GRENIER', '', '0688900091', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '87', ' cours de la somme ', '33800', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '0607491915', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'chemin de la gaillarde ', '33710', 'TEUILLAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'GITTON', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '31', ' r Gutenberg ', '33400', 'TALENCE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'NOUZEILLES', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '52', ' allee du pas douen ', '33370', 'BONNETAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'FOUCHE', '', '', 'Veronique.Geneste@caissedesdepots.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '17', ' alle des foucheres ', '33240', 'SAINT ANDRE DE CUBZAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BORDESSOULES', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '59', ' rue de la cassadotte ', '33450', 'IZON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BEAUQUIS / RENAUD-LYAT', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '10C', ' rue Alexis Puyo ', '33160', 'SAINT MEDARD EN JALLES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'COTARD', '', '0633716267', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2', ' chemin de Teyché ', '33480', 'CASTELNAU DE MEDOC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DUFIN', '', '0678269127', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '8', ' palus ', '33210', 'COIMERES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DALLAVALLE', '0953535610', '0631527316', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '18', ' avenue Gustave Eiffel ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'FINANSO France', '0972422908', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33000', 'BISCAROSSE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BOUZIGE', '0608929600', '0684418066', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' lieu dit le hageot ', '33410', 'CARDAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'AZNAR Victor', '', '0624352067', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '10C', ' rue Alexis Puyo ', '33160', 'SAINT MEDARD EN JALLES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'CHOTARD', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Talon ', '17360', 'SAINT MARTIN DE COUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'TESSIER Michel', '0546042191', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '3', ' la Guillade ', '33920', 'CIVRAC DE BLAYE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DECOUZON', '', '0608427726', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '61', ' cours Saint Louis ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'Nicolas-Gaston Ellie', '', '0686071285', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '9', ' rue Poilus ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'DELEST', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '', 'LIBOURNE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CASTAGNA', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '17', ' rue de la Tourasse ', '33750', 'Saint Quentin de Baron');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'DUTILLEUL Jonathan / DHELLIN Alexia', '', '0644018124', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '110', ' avenue du Peyrou ', '33370', 'ARTIGUES PRES BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '129', ' rue jules Guesde, résidence monte cristo ', '33270', 'FLOIRAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'CAMOU JUNCAS Annie', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '18', ' chemin de Paguemaou ', '33360', 'CAMBLANES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'MARCADIER', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '10 bis', ' place de l''église ', '33920', 'SAINT CHRISTOLY DE BLAYE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'MARCHAND Philippe', '0557424695', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '50', ' rue de la lande ', '33240', 'SAINT GERVAIS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'MARCHAIS', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '16', ' route de Lenan ', '33138', 'LANTON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'HARNIST Pascal', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '110', ' avenue du Peyrou ', '33370', 'ARTIGUES PRES BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Résidence Rosiers Bellevue A2 ', '33170', 'GRADIGNAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'VALLE Batiste', '', '0661469112', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33', 'EYSINES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'PRIE', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Chateau Blanzac ', '33350', 'SAINT MAGNE DE CASTILLON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'DANIELLE PONS', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '10', ' route du chateau d''eau ', '33390', 'PLASSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'LOVERDE', '0557420226', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '63', ' route de germignan ', '33160', 'SAINT AUBIN DU MEDOC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'LATORRE', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Chemin bremontier ', '33880', 'CAMBES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'L''EGLISE', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '3', ' rue de la Hortie ', '33240', 'SAINT GERMAIN DE LA RIVIERE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'THIBAUD', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '90', ' route de Coirac ', '33540', 'GORNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'LAMOUROUX', '', '0622447578', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'BP 40 ', '33034', 'BORDEAUX Cedex');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '13 bis', ' avenue Aristide Briand ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'COCHET Antoine', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33170', 'SAIN MEDARD');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'ROUX', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2AA', ' LA NAUZE ', '33580', 'SAINT FERME');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '9', ' rue des glycines ', '33112', 'SAINT LAURENT DU MEDOC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'BESTES LARROQUE', '', '0673014607', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '6', ' rue ferdinand Lafargue ', '33780', 'SOULAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '5', ' Rue De La Paix ', '33150', 'CENON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '0631034943', 'christophehardy.lmba@wanadoo.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Rue des huttiers ', '33980', 'AUDENGE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'GARLOPEAU / RUIZ ', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '4', ' rue Amiral Courbet ', '33740', 'ARES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'PEKKERIN Noëlle', '', '0642957627', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', ' route du preuilh ', '', '');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'KOLTZ / RAMBAUD', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '106', ' route des graves ', '33640', 'PORTETS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'DELBREL', '', '0609229196', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '17', ' rue des pavillons ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'REYDON', '', '0661483366', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '119', ' rue jean Gaujon ', '33160', 'SAINT MEDARD EN JALLES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'PRENEUX', '', '0631371547', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '9', ' bis rue Francis Jammes ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'VEZIN Sandra', '', '0684897608', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '174', ' avenue du Truc BP 60275 ', '33697', 'MERIGNAC Cedex');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '0556124141', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '108', ' rue Nancel Penard ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'BUFFARD', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' chez Dehors ', '17270', 'NEUVICQ');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BERGERON Fabrice', '', '0687238555', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '202', ' av Pasteur ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'COUVREUR Didier', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Avenue Aristide Briand ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'CABROL', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '15', ' rue des Vignobles ', '33240', 'SAINT ROMAIN LA VIREE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'MOCQUILLON', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '', '');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'BERNARD Alexia', '', '0675954394', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'rue Emile Zola ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'SERINDAT / BERTON', '0664485232/0637669133', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '80', ' rue du Monralieu ', '33320', 'EYSINES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BOSQ Bruno', '', '0786014720', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '15', ' rue fouineyre ', '33290', 'Luçon médoc');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'Ferreira Dias', '', '0760073108', 'dilma_87_lol@hotmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '15', ' résidence Edouard Dorc ', '33390', 'BLAYE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'SAJANT', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '', '');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'LAUNAY Benjamin', '', '0629355395', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '251', ' avenue de la marne ', '33700', 'MERIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'GOGUET', '', '0618512847', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' Rue Gallieni ', '33780', 'SOULAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '0961270735', '', 'sarl.dubouilh@wanadoo.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33140', 'VILLENAVE D''ORNON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'ELIAS Vincent', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Lieu dit GAVES, Laroque ', '33410', 'CADILLAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'VENDRASCO', '', '0680584136', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '173', ' avenue Jean Cordier ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'ALBERTINI', '', '', 'thibault.albertini@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Chateau la Baronnerie ', '33620', 'CEZAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'DEYZAC', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '31', ' Avenue André Lafon ', '33820', 'SAINT CIERS SUR GIRONDE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DIAS Alain', '0557327592', '0669158975', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '8', ' hERV2 ', '33920', 'SAINT CHRISTOLY DE BLAYE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'FOUCHET Alain', '0557425823', '0667189264', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '20', ' rue de romainville ', '33700', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'LE GALL', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '10', ' allée ronsard ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'PANCHEVRE', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '14', ' bis route de lucrabey ', '33250', 'CYSSAC MEDOC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'ROJO', '', '0611321998', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Les terres d''Abzac, lieu dit Petit Piron ', '33230', 'ABZAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'BEZIES', '', '0614901579', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Les Ourmes ', '33990', 'HOURTIN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'BERJAL', '', '0772910929', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Allée de niki ', '33160', 'SAINT MEDARD');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'URBANO', '0670233276', '0699024627', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Allée de niki ', '33160', 'SAINT MEDARD');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'GABRIEL / SERRE', '', '0626269883', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'allée de niki ', '33160', 'SAINT MEDARD');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'ARZILLER / CINUS', '0670233276', '0699024627', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '91', ' Rue Principale ', '33820', 'ETAULIERS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '38', ' avenue du luxembourg ', '33700', 'Merignac');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'FULCHIRON', '', '0695244834', 'Jimmyfb@yahho.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '11', ' chez le maure ', '17210', 'ORIGNOLLES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'AUDUBERTEAU Eric', '', '060317078', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '18', ' rue Pascal Mothes ', '33800', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '24 bis', ' rue Antoune ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'FOURNEREAU', '', '0685109935', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '16', ' rue vincent Vangogh ', '33650', 'SAINT MEDAD D''EYRANS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'ETCHEBERYGARAY', '0556727754', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '11', ' av Louis Barthou ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'DURAND', '', '0675390400', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '35', ' route du lavoir ', '33710', 'COMPS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'TOMASELA', '', '0615640176', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' butte des juins ', '33390', 'BERSON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'LEMELLE', '', '0608423520', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2', ' lotissement bicou ', '33240', 'SALIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'JAUBERT', '', '0665620701', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', ' rue de l''esperance ', '33930', 'MONTALIVET');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'CAHILAU Julie', '', '0674877869', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '9', ' rue des chasselas ', '33180', 'SAINT ESTEPHE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'PREVOT', '', '0604452978', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '12', ' rue de la gare ', '33299', 'LUDON MEDOC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'DUCAMP', '', '0612576504', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '21', ' rue de brazza ', '33700', 'MERIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'DUC', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '140', ' rue des pinsons ', '40', 'BISCAROSSE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CLAIROTTE', '', '0608269546', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '100', ' rte de coutras ', '33910', 'SAINT DENIS DE PILE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'MASSOT', '0557923236', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '23', ' impasse Nougueyrau ', '33450', 'IZON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2', ' rue Saint Denis ', '86000', 'POITIERS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '0781233045', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' route des salmondieres ', '86800', 'JARDRES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '0683804321', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '372', ' chemin de pillon ', '33880', 'BAURECH');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'KOENIG', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '6', ' rue andre clerc ', '33390', 'SAINT MARTIN LACAUSSADE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'PASQUES', '', '0626265181', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' chemin du Maine de Laborde ', '33450', 'SAINT LOUBES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'SABLE Lisa', '', '0644236826', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' chemin du Maine de laborde ', '33450', 'SAINT LOUBES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'SABLE Estelle', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '61', ' route du tasta ', '33450', 'SAINT SULPICE ET CAMEURAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BLONDEL Nicolas', '', '0635490034', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '230', ' route de libourne ', '33240', 'SAINT ANDRE DE CUBZAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '0557422613', '0651491373', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '64 bis', ' Av Louis Didier ', '33240', 'LIBOURNE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'CASTAGNA', '', '0620582228', 'danielle.castagna@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Lieu dit bras de fer ', '33920', 'CIVRAC DE BLAYE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DECOMBE', '', '0682204445', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '9', ' chemin duburdieu ', '33610', 'CESTAS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'CRESP', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '3801', ' route de Dax ', '40350', 'POUILLON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'DECLA', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '57', ' rue de balzac ', '33000', 'TALENCE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'DAUGUET Caroline', '', '0682131139', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '8', ' rue de l''école ', '33240', 'SAINT GEES DE FRONSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'MONBARBUT', '', '0686784463', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' jartot ', '33620', 'LARUSCADE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'LARROUTUROU', '', '0683832563', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '20', ' rue de Metz ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'CARON', '', '0607164656', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '34', ' chemin de Tarreyrots ', '33240', 'SALIGNAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'AUDINETTE', '', '0627473457', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '12', ' avenue de Verdun ', '33480', 'MIOS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'ROUSSEAU', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '110', ' avenue du Peyrou ', '33370', 'ARTIGUES PRES BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33600', 'Pessac');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'SIRIEX', '', '', 'Siriex33600@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '50', ' rue Valentin Bernard ', '33710', 'Bourg sur Gironde');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'BERNARD', '0557682871', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Rue de Gascogne ', '33160', 'Saint medard en jalles');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BRUNE BARBE', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '25', ' av Bel Air ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'BANOS', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1éA', '12A av de Verdun ', '33380', 'MIOS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'ROUSSEAUX', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' chemin des collines ', '33270', 'BOULIAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'FAVIER', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '15', ' rue du Bosquet de Venteille ', '33185', 'LE HAILLAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DELGADO', '0556027570', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '70', ' chemin du broutey ', '33240', 'SAINT ROMAIN LA VIREE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'PASSEREAU', '', '0662290243', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2', ' avenue cassiopee ', '33160', 'Saint medard');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'BEYNEL', '', '', 'p.beynel@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '21', ' rue castros ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'LARAN', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '47', ' route de coutras ', '24700', 'LE PIZOU');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'TERRYN', '', '0670160852', 'dominique-terryn@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '4', ' barail des robins ', '33920', 'SAINT GIRON D''AIGUEVIVES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'VIEN', '', '0631442962', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '10', ' rue Gabriel Faure ', '33000', 'EYSINES');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'JAILLET', '', '0662749446', 'leonore.jaillet@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '30', ' rue Xaintrailles ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'LEJET', '', '0660269489', 'vlm47@orange.fr',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Lieu dit GAVES LAROQUE  CADILLAC ', '33410', 'CADILLAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'PICOT', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1 bis', ' route de la vallée ', '33670', 'CURSAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'SERCLERAT', '', '0674626424', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Z.A.C. Haut Madère - 2 ', '', '');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '0616598058', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '34', ' l''oiseau ', '33126', 'FRONSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'PENARD', '', '0609354169', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '5', ' allée des pensées ', '33', 'LANTON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'PREVEAU', '', '0680446407', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '82', ' av de MAGONTY ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'BELLOC', '0556071774', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '26', ' rue des Frères Lumière ', '33560', 'CARBON BLANC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', '', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '6', ' rue Dansperre ', '33720', 'VERLADE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'NGOUANDZI', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '53 bis', ' route du liard ', '33340', 'SAINT GERMAIN D''ESTEUIL');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'LUCEYRAN', '', '0676149993', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' route lassalle ', '33930', 'VENDAYS MONTALIVET');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'GALANT', '', '0671507595', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '18', ' rue de Leyssaut ', '33990', 'HOURTIN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'BARRET', '', '0671814243', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '52', ' passage du jeune ', '33780', 'SOULAC SUR MER');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'BASSIBEY', '', '0684509298', 'laurent.bassibey@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'ZA DU BEDAT ', '33650', 'ST MEDARD DEYRANS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'GIB CONSTRUCTION', '0557961242', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', ' ', '33000', 'SAINT JEAN D''ILLAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'DARMAILLACQ', '', '0665157237', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '3', ' allee des pensées ', '33000', 'LANTON');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'BOURBON PALLAS', '', '0630726748', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '15', ' avenue Johan Strauss ', '33510', 'ANDERNOS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'PRIEUR', '', '0617308527', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '17', ' domain de de castelnau ', '33490', 'SAINT PIERRE D''AURILLAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'THOUESNY', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '95', ' avenue Léon Blum ', '33110', 'LE BOUSCAT');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'SIERRA', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '36', ' avenue Jean Luc Vonderheyden ', '33460', 'ARSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'TAUZIER Florian', '', '0629757552', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '11', ' les grands regniers ', '33220', 'EVNESSE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'BOS', '', '0610861529', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Contrelaoude ', '33990', 'HOURTIN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'GIRY', '', '0611157007', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '8', ' rue Ulysse Gayon ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mr', 'DUPONT', '', '0672468096', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '7', ' rue Emile Dreux ', '33200', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'MERLET', '', '0627301413', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '58', ' route de Bordeaux ', '33220', 'PORT SAINTE FOY');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'PARTEDIS', '0553242323', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '46', ' rue Thedore DUCOS ', '33000', 'BORDEAUX');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'CROCKETT Guylaine', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '', 'Av Robert Schumann ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'STEVENS', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2', ' rue Descartes ', '33000', 'VILLENAVE');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'MIRAMONT', '', '0688726829', 'mirchristi@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '3', ' résidence le chateau ', '24700', 'LE PIZOU');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'DARRAS', '', '0686621094', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '504', ' rue voltaire ', '33290', 'LE PIAN MEDOC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'BON Sylvie', '', '0687567645', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '37', ' avenue de Brivazac ', '33600', 'PESSAC');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'NAU', '', '0614515321', 'plombimpact@gmail.com',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '2', ' place Deutsch de la Meurthe ', '33170', 'GRADIGNAN');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'MrMme', 'REMY', '', '0662440008', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '3', ' Rue haute ', '25870', 'AUXONS DESSOUS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), '', 'BORTOLIN', '', '', '',currval('adresse_sequence'));
insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '1', ' place barbey vieux ', '33640', 'ARBANATS');
insert into client(id, civilite, nom, telephone, portable, email, adresse_id) values (nextval('client_sequence'), 'Mme', 'TESSIER-GUY Delphine', '', '', '',currval('adresse_sequence'));

insert into adresse(id, numero, voie, code_postal, commune) values (nextval('adresse_sequence'), '17', 'avenue Aristide Briand ', '33600', 'PESSAC');
insert into entreprise(id, nom, adresse_id, siret, heure_ouverture, heure_fermeture, search_distance, search_days, temps_rdv, jours_ouverture, time_step) values (1, 'Samson Multi Services', currval('adresse_sequence'), '54205118000066', '08:00:00', '19:00:00', 20, 45, 90, 124, 30);
